[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#667EEA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
